# #==========================================================
# # Static provisioning
# #==========================================================
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: blob-pv-static
#   labels:
#     app: myapp
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""  # ← 빈 문자열 (StorageClass 사용 안 함)
#   csi:
#     driver: blob.csi.azure.com
#     readOnly: false
#     volumeHandle: terzmyaksstg_app-data  # ← 고유한 ID
#     volumeAttributes:
#       protocol: fuse
#       containerName: app-data
#       secretName: azure-storage-secret
#       secretNamespace: dev
#     nodeStageSecretRef:
#       name: azure-storage-secret
#       namespace: dev
